# Generated by Django 5.1 on 2024-09-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_news_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
