# Generated by Django 5.1 on 2024-09-23 11:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_new_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category_images/default_image.jpg', upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
