# Generated by Django 5.1 on 2024-10-05 05:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_subscription_alter_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lokhitmovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='epaperdaily',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='new',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
