# Generated by Django 5.1 on 2024-10-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_lokhitmovement_alter_epaperdaily_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=20),
        ),
    ]
