# Generated by Django 5.1 on 2024-10-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_url',
            field=models.URLField(blank=True),
        ),
    ]
