# Generated by Django 5.1 on 2024-10-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_category_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_url',
            field=models.CharField(max_length=100),
        ),
    ]
