# Generated by Django 4.0.1 on 2024-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_epaperdaily_name_alter_new_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokhitmovement',
            name='name',
            field=models.CharField(default='Lokhit Movement', max_length=255),
        ),
        migrations.AlterField(
            model_name='epaperdaily',
            name='name',
            field=models.CharField(default='E Papers Daily', max_length=255),
        ),
    ]
